version: '3'
services:
  mica:
    image: obiba/mica:snapshot
    ports:
      - "8445:8445"
      - "8082:8082"
    links:
      - mongo
    environment:
      - JAVA_OPTS=-Xmx2G
      - MICA_ADMINISTRATOR_PASSWORD=${MICA_ADMINISTRATOR_PASSWORD}
      - MICA_ANONYMOUS_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - OPAL_HOST=opal
      - OPAL_PORT=8443
      - AGATE_HOST=agate
      - AGATE_PORT=8444
    volumes:
      - ${PROJECT_HOME}/mica_home:/srv
  opal:
    image: obiba/opal:latest
    ports:
      - "8443:8443"
      - "8080:8080"
    links:
      - mongo
      - agate
      - rserver
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=${OPAL_ADMINISTRATOR_PASSWORD}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - AGATE_HOST=agate
      - AGATE_PORT=8444
      - RSERVER_HOST=rserver
    volumes:
      - ${PROJECT_HOME}/opal_home:/srv
  mongo:
    image: mongo:4.2
  agate:
    image: obiba/agate:latest
    ports:
      - "8444:8444"
      - "8081:8081"
    links:
      - mongo
    environment:
      - AGATE_ADMINISTRATOR_PASSWORD=${AGATE_ADMINISTRATOR_PASSWORD}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    volumes:
      - ${PROJECT_HOME}/agate_home:/srv
  rserver:
    image: obiba/opal-rserver:latest
    volumes:
      - ${PROJECT_HOME}/rserver_home:/srv
